export const ROUND_STATE_DEAL = 'ROUND_STATE_DEAL';
export const ROUND_STATE_FLOP = 'ROUND_STATE_FLOP';
export const ROUND_STATE_TURN = 'ROUND_STATE_TURN';
export const ROUND_STATE_RIVER = 'ROUND_STATE_RIVER';
export const ROUND_STATE_OVER = 'ROUND_STATE_OVER';
